### ISSUE TITLE
I really can't understand its pronunciation。

### ISSUE THREAD

**Issue by JuneFire** [N3ther/Algonquin-TTS#5]
When I input a sentence phonetic symbol, I can't understand its pronunciation。Where did you download the pronunciation file in the folder “default”?

It's too harsh，and Incoherent pronunciation。Can you continue to improve? Or tell me where to download the phonetic symbols, and I will improve them。
My email is chengzhikang2015@163.com.

**Comment by thetacola** [comment]
That's something I'm planning on fixing next update, I recorded them a few months ago, but I didn't quite clip them correctly, so some sounds lost parts or had part of a vowel still attached to them. Should be fixed in ~a week when I can re-record the sounds.

**Comment by thetacola** [comment]
Now that I think about it a bit more, I think I'm going to attempt a different way of making the sounds in question, the way I'm currently doing it doesn't sound all that natural mainly because it's only picking single phonemes and making every phoneme a syllable. If I simulate it instead, it should be much more understandable and naturalistic.

**Comment by thetacola** [comment]
Issue should be fixed in v0.2.0, please re-open if it is still not fixed.
